services:
  app:
    image: system-monitoring:1.0
    ports:
      - 8080:8080

  prometheus:
    image: prom/prometheus:v2.37.0
    ports:
      - 9090:9090
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:9.0.7
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  prometheus-data:
  grafana-data:
