{
 "title": "Monitoring",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "freq", "label": "Frequency", "query": { "query": "label_values(freq)" } },
   { "name": "cpu", "label": "CPU", "query": { "query": "label_values(cpu)" } },
   { "name": "motherboard", "label": "Motherboard", "query": { "query": "label_values(motherboard)" } },
   { "name": "slot", "query": { "query": "label_values(slot)" } }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(cpu) (machine_cpu_loading{cpu=\"$cpu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "machine_cpu_cores_total{cpu=\"$cpu\"}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "machine_cpu_threads_total{cpu=\"$cpu\"}"
    }
   ]
  },
  {
   "title": "Vendor Frequency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "machine_cpu_vendor_freq_total{cpu=\"$cpu\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 17, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "machine_cpu_temperature{cpu=\"$cpu\"}"
    }
   ]
  },
  { "title": "Motherboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Motherboard",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "machine_motherboard_name_total{motherboard=\"$motherboard\"}"
    }
   ]
  },
  {
   "title": "BIOS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "machine_bios_name_total{motherboard=\"$motherboard\"}",
     "legendFormat": "{{bios}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    { "expr": "machine_memory_consumption", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Type",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 24 },
   "repeat": "slot",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "machine_memory_type_total{slot=\"$slot\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 24 },
   "repeat": "slot",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "machine_memory_capacity_total{slot=\"$slot\"}",
     "legendFormat": "{{capacity}}"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 24 },
   "repeat": "slot",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "machine_memory_speed_total{slot=\"$slot\"}",
     "legendFormat": "{{speed}}"
    }
   ]
  },
  {
   "title": "Slot",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 24 },
   "repeat": "slot",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "machine_memory_slot_total{slot=\"$slot\"}",
     "legendFormat": "{{slot}}"
    }
   ]
  },
  {
   "title": "Manufacturer",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 24 },
   "repeat": "slot",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "machine_memory_manufacturer_total{slot=\"$slot\"}",
     "legendFormat": "{{manufacturer}}"
    }
   ]
  }
 ]
}